name: adaptive-spin-evolution
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pybind11=2.10
  - pip>=21.3 #For editable installationhttps://pip.pypa.io/en/latest/reference/build-system/pyproject-toml/?highlight=project%20toml#editable-installation
  - numpy>=1.16
  - scipy>=1.0
  - matplotlib>=1.2.1
  - pytest>=5.3
  - pytest-rerunfailures>=5.3
  - pymeep=1.24
  - pymeep-extras=1.24
  - pyscf=2.0.1
  - pip:
    - pyscf[geomopt]==2.0.1