[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.6.1"]
build-backend = "setuptools.build_meta"

[project]
name = "pyket"
description = "Adaptive code for pyket"
dynamic = ["version"]
dependencies = [
    "test",
    "pytest"
]


[tool.setuptools]
zip-safe=false



